### ISSUE TITLE
Can't build properly in jdk8

### ISSUE THREAD

**Issue by dkowis** [rackerlabs/api-checker#265]
This is very strange, at first I thought it was an artifact of the work I was trying to do to split up a scala 2.10 and 2.11 artifact. Unfortunately, it happens in master as well.

The scala maven plugin (at least I think it's this plugin) seems to build java 8 artifacts no matter what. I will get this error reliably, if I use jdk8 to build the software.

```
Tests in error: 
  com.rackspace.com.papi.components.checker.RequestResponseSuite: com/rackspace/com/papi/components/checker/util/DateUtils : Unsupported major.minor version 52.0
```

So, there should probably be some maven restriction to ensure you're using JDK7 no matter what.

**Comment by RackerWilliams** [comment]
That's weird.  Usually, you get the unsupported major.minor when you try to serialize/use class compiled with a newer version of the JDK. It's interesting that it's happening in DateUtils -- which is the only class that's written in Java...

https://github.com/rackerlabs/api-checker/search?l=java

What I think is happening here is that you're switching the scala compiler to generate 1.7 classfiles and the Java compiler is using 1.8 or vice-versa.

Surely you can tell either to target 1.7 or 1.8...but I guess you'd have to coordinate.

**Comment by dkowis** [comment]
Yep, went down that rabbit hole already. You can specify `-target:jdk7` to the scalac, tried all that in various locations of the maven poms trying to get the maven-scala-plugin to build jdk7 classes.
```
$ scalac -target
scalac error: Usage: -target:<target>
  where <target> choices are jvm-1.5, jvm-1.5-fjbg, jvm-1.5-asm, jvm-1.6, jvm-1.7, msil (default: jvm-1.6)
```

I also modified the build to do dual java/scala builds like recommended on the scala maven plugin site, and then when the java classes ran to compile it warned about the same thing... Something is fishy.

**Comment by RackerWilliams** [comment]
Just so that I understand.

Scala 2.10 can generate up to jvm 1.7 format
Scala 2.11 can generate up to jvm 1.8 format

So when compiling on scala 2.11 you want to compile 1.8 classes and on 2.10 you want to compile 1.7 classes. 

So what's happening is that on 2.10 build you're generating 1.7 classes, but DateUtil gets compiled to 1.8 and tests try to run with 1.7 so things blow up.  Right?

You know, you could convert that one class from Java to Scala and just deal with one compiler 😈
Really it's a simple utility class we stole...(uh borrowed) from Apache HTTP Client...

**Comment by dkowis** [comment]
Nope. That's not quite right.

I'm trying to build everything for jdk 1.7. If I'm using JDK8 things fail (whether doing scala 2.11 or 2.10). If I'm using JDK7 (regardless of 2.11 or 2.10 again) it works fine. I verified this failure on master, which only uses 2.10 right now anyway.

It might be simpler to disable the java compiler for that one class and just let scalac deal with it. Maybe it'd work right, but I'd be nervous that it's generating 1.8 classes.

**Comment by RackerWilliams** [comment]
That's really weird.

You know converting the java class to scala..wouldn't be so hard....

http://javatoscala.com/

**Comment by RackerWilliams** [comment]
Do you get the version error when you run tests?  Or when?  How can I replicate it?

**Comment by dkowis** [comment]
Use JDK8, run `mvn test`.

It should bomb on you.
